/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ddl-1.1.2 */
#ifndef VERSION_ddl
#define VERSION_ddl "1.1.2"
#endif /* VERSION_ddl */
#ifndef MIN_VERSION_ddl
#define MIN_VERSION_ddl(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 2)
#endif /* MIN_VERSION_ddl */
/* package array-0.5.4.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.4.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 4)
#endif /* MIN_VERSION_array */
/* package base-4.17.2.1 */
#ifndef VERSION_base
#define VERSION_base "4.17.2.1"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package indents-0.5.0.1 */
#ifndef VERSION_indents
#define VERSION_indents "0.5.0.1"
#endif /* VERSION_indents */
#ifndef MIN_VERSION_indents
#define MIN_VERSION_indents(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_indents */
/* package parsec-3.1.16.1 */
#ifndef VERSION_parsec
#define VERSION_parsec "3.1.16.1"
#endif /* VERSION_parsec */
#ifndef MIN_VERSION_parsec
#define MIN_VERSION_parsec(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 16)
#endif /* MIN_VERSION_parsec */

/* tool alex-3.5.2.0 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.5.2.0"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  5 || \
  (major1) == 3 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-13 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "13"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  13 || \
  (major1) == 13 && (major2) <  0 || \
  (major1) == 13 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.4.8 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.4.8"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.4.8 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.4.8"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.27.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.27.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  27 || \
  (major1) == 2 && (major2) == 27 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.1.5 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.1.5"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool pkg-config-1.8.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "1.8.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.4.8 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.4.8"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  4 || \
  (major1) == 9 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.42 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.42"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  42 || \
  (major1) == 2 && (major2) == 42 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ddl-1.1.2-GTxCW75DI4ODRSTsDqvSoz-ddl"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.1.2"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
